Allow reconnect by resetting 'pending'
WalletConnect/walletconnect-monorepo pull request #370
Opened 2020-10-09 08:58 UTC by geigerzaehler

Before, calling `connect` after `killSession` did not open the modal and reconnect. The issue was that the value of `pending` was never reset to `false` after the connection was established.

2020-10-09 14:28 UTC, pedrouid requested changes

2020-10-09 14:28 UTC, pedrouid commented on packages/clients/core/src/index.ts
> +    this._pending = value;
this should still be empty

2020-10-09 14:28 UTC, pedrouid commented on packages/clients/core/src/index.ts
> +    this.pending = true;
this should be set on the private variable `this._pending`

2020-10-09 14:28 UTC, pedrouid commented on packages/clients/core/src/index.ts
> +      this.pending = false;
same as above

2020-10-11 12:06 UTC, merged

2021-02-08 14:26 UTC, NunoAlexandre commented
@pedrouid @geigerzaehler I have just tried running the latest released version, `1.3.5` and this issue seems to persist.

2021-02-09 15:48 UTC, pedrouid commented
tbh I think reconnecting is advised against

it's much easier to just create a new connector

WalletConnect v1.0 clients weren't really designed for connecting and reconnecting since the connectors were designed for a single session usage

2021-02-09 15:59 UTC, NunoAlexandre commented
Thanks for your reply, @pedrouid. That is the approach I went with @ https://github.com/radicle-dev/radicle-upstream/pull/1591. 

The specific issue we are experiencing is that once the QR Code modal is triggered if it is dismissed, follow-up attempts to trigger it again won't do anything whatsoever. 

That seems like a bug rather than a design decision tho. The workaround used in the linked PR involves detecting a dismissal of the modal and create a new instance of `WalletConnect` in that case, which also needs to happen when the user disconnects their wallet.